//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductManagementEntities : DbContext
    {
        public ProductManagementEntities()
            : base("name=ProductManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductTbl> ProductTbls { get; set; }
        public virtual DbSet<Usertbl> Usertbls { get; set; }
        public virtual DbSet<Logintbl> Logintbls { get; set; }

        public System.Data.Entity.DbSet<ProductManagementSystem.Models.ProductModel> ProductModels { get; set; }
    }
}
