//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ProductManagementSystem.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ProductTbl
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter Product Category")]
        public string ProductCategory { get; set; }

        [Required(ErrorMessage = "Please enter Product Name")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Please enter Product Price")]
        public string ProductPrice { get; set; }

        [Required(ErrorMessage ="Please enter Product Quantity")]
        [Range(0,99,ErrorMessage ="Quantity must be numeric")]
        public int ProductQuantity { get; set; }

        [Required(ErrorMessage ="Please enter Short Product Description")]
        public string ShortDesc { get; set; }

        [Required(ErrorMessage = "Please enter Long Product Description")]
        public string LongDesc { get; set; }

        [Required(ErrorMessage ="Please upload Image file")]
        public string SmallImage { get; set; }

        [Required(ErrorMessage = "Please upload Image file")]
        public string LargeImage { get; set; }
    }
}
