//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_Management_SystemEntities : DbContext
    {
        public Hotel_Management_SystemEntities()
            : base("name=Hotel_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookingstbl> Bookingstbls { get; set; }
        public virtual DbSet<Hotelstbl> Hotelstbls { get; set; }
        public virtual DbSet<Roomstbl> Roomstbls { get; set; }
    }
}
