//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roomstbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roomstbl()
        {
            this.Bookingstbls = new HashSet<Bookingstbl>();
        }
    
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public Nullable<decimal> RoomPrice { get; set; }
        public Nullable<bool> RoomIsActive { get; set; }
        public Nullable<System.DateTime> RoomCreatedDate { get; set; }
        public string RoomCreatedBy { get; set; }
        public Nullable<System.DateTime> RoomUpdatedDate { get; set; }
        public string RoomUpdatedBy { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string RoomCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookingstbl> Bookingstbls { get; set; }
        public virtual Hotelstbl Hotelstbl { get; set; }
    }
}
